### ISSUE TITLE
question about simulation

### ISSUE THREAD

**Issue by moritz2212** [rolfjoseph/open-websoccer-tlc#1]
Hallo,

wie werden die Spiele genau simuliert, in ihofmann version klappt das irgendwie nicht. Ich habe 40 Ligen und möchte dementsprechend die Spiele pro Spieltag simulieren, leider hängt es irgendow und ich finden nicht woran es hängt. Könnt Ihr mir helfen?

**Comment by rolfjoseph** [comment]
Nun, zuerst ist dies kein Supportforum. Fragen kann man auf http://websoccersim.com/forum/ stellen. Die Frage ist sehr allgemein gestellt und zudem das Problem nicht genau geschildert. Stelle bitte also die Frage im oben angegebenen Forum und beschreibe denn Sachverhalt genauer.

In der Regel liegt es am eigenem Server oder man will zu viele Spiele gleichzeitig simulieren. Auch Add-On´s können dieses Verhalten auslösen. Bei 40 Ligen sollten diese nach meiner Erfahrung je 2 Ligen im halbstündigen Abstand simuliert werden, da es sonst zu Überschneidungen kommen kann, was die Rechenzeit entsprechend verlängert und zum Teil zu Stillstand der Simulation führen kann.

Bei so vielen Spielen, müssten diese wohl eher ganz simuliert werden, so das es also keine Livspiele geben wird.

Es ist also komplizierter und ein Webspace wird da wohl nicht reichen. Wie es genau simuliert wird ist daher nicht die Frage. Eine Simulationsinstanz wird bei einer Rechenzeit von 5 Minuten abgebrochen. Bei mir brauchten 10 Spiele in 5 Minuten-Stimulationsintervall bis höchsten 2,5 Minuten. Erst Recht, wenn es Livespiele sind, wo ständig Änderungen gemacht werden.

Mann darf auch die Datenbanktransaktionen nicht außer acht lassen. Nach jedem Spiel werden in vielen Tabellen Abschlußeinträge gemacht. Daher braucht man auch generell eine schnelle Datenbankanbindung, um die vielen Live-Einträge verarbeiten zu können, die alle 5 Minuten anfallen ( bei Standardsimulation ).

20 Spiele gleichzeitig simulieren ist meist die Obergrenze.

Support-Anfragen werden also hier nicht beantwortet !
