### ISSUE TITLE
FS-Spiele & Heutige Spiele 

### ISSUE THREAD

**Issue by bihline** [rolfjoseph/open-websoccer-tlc#2]
Hello,

I saw on Your site http://manager.topligclub.de/websoccer/ that you made "FS-Spiele (friendy matches)" and on home page "Heutige Spiele (Today Matches)". 
I'm trying to do that on my site, but i need some directions, so can You help me or if you can upload your modules for that.

Thanks a lot.

**Comment by rolfjoseph** [comment]
"FS-Spiele (friendy matches)"  ist not a part of openwebsoccer. The site based on HSE Websoccer with my additions. "FS-Spiele (friendy matches)"  is not opensource. Have a look on my site http://manager.topligclub.de/openwebsoccer/ there is no "FS-Spiele (friendy matches)".

"Heutige Spiele (Today Matches)" ist a tricky derivat of the same "Heutige Spiele (Today Matches)" under the menu. I think, at one of the next steps it will be included with a choise of activation.

**Comment by bihline** [comment]
Ok, thanks
I will try to make "FS-Spiele (friendy matches)" modul, like as Youth Team matches.. so so much work to do. openwebsoccer is great script and it needs this "friendy matches" module.

**Comment by rolfjoseph** [comment]
Yes, i think that´s the right way to code "FS-Spiele (friendy matches)".

**Comment by bihline** [comment]
I'm sorry to bother you, do you know whose this page http://manager.topligclub.de/websoccer/
maybe he can help us a little to make this FS modul

**Comment by rolfjoseph** [comment]
Yes, thats my websoccer site. The site based on HSE Websoccer with my additions.
Have a look on my site http://manager.topligclub.de/openwebsoccer/ there is no "FS-Spiele (friendy matches)". You can switsch it afther your login to openwebsoccer path.

I have not so match time, so the friendly modul comes not up at nearly time.

**Comment by bihline** [comment]
Okay. Thanks a lot.
